server:
  port: 8090

# ===================================================
# Configuracion en MySQL y JPA
# ===================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafeteria?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ===================================================
# Twilio
# ===================================================
twilio:
  account_sid: AC407a349fb1e5572a3b6b53f9e4237aeb
  auth_token: a4a8f9da208d22ca99de9d4bd1f28eb5
  trial_number: +15074167933