server:
  port: 8090

# ===================================================
# Configuracion en MySQL y JPA
# ===================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafeteria?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true